version: '3.8'

services:
  app:
    build:
      # context: ./nest-api
      dockerfile: Dockerfile
    container_name: swapi-gql
    environment:
      - PORT=3000
      - DB_HOST=db
    ports:
      - '3000:3000'
    depends_on:
      - db
    volumes:
      - ./src:/user/src/app/src

  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=pass123
    container_name: swapi-gql-db
    volumes:
      - pg-volume:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    command: postgres -c 'max_connections=1000'

volumes:
  pg-volume:
